### ISSUE TITLE
LaserScan cannot be recorded

### ISSUE THREAD

**Issue by luyang00** [ros2/rosbag2#202] opened 2019-11-11 03:15 UTC
Hi,
I'm trying to record a rosbag for slam testcase. In my test, IMU message has been recorded and replay normally but sensor_msgs/laserscan seems not recorded properly. The replay of this bag only have IMU message. 
Then I try to only record laserscan message, the data size of this bag still not grow, so I guess it didn't write into a rosbag file but the log from rosbag2 on screen shows this topic has been subscribed successfully.  I am pretty sure my laserscan topic has data and can be subscribed correctly.
Test on rosbag2 binary version at ros2-dashing.

**Comment by Karsten1987** [comment] 2019-11-11 16:58
I think this is a duplicate of https://github.com/ros2/rosbag2/issues/201.
I'll close this topic as I believe the matter can be discussed on the other issue. Feel free to re-open this ticket if you feel that it's fundamentally different.

**Closed by Karsten1987** 2019-11-11 16:58 UTC
Labels: duplicate

**Comment by mkhansen-intel** [comment] 2019-12-04 01:56
I'm running into this same issue, the /scan topic is being published by Gazebo, but I can't record it.

The issue you linked looks different to me, in that the fix was to the demo being used. I think this actually duplicate of #125 

I'll comment there
