### ISSUE TITLE
Snapshot Mode with Duration

### ISSUE THREAD

**Issue by johnsonTyler0511** [ros2/rosbag2#1795] opened 2024-08-28 17:45 UTC
## Description
I am using ros2 bag record in snapshot-mode and I want to be able to use both a max size for the bag file and a duration to split the bag files up by.

Currently with snapshot-mode and setting a max_bag_duration I end up getting bag files with no messages but has some metadata about topics etc. 

it would be great if the bag files would not be created until the snapshot service was called and then they get split by duration and size as normal :+1: 

## Completion Criteria

snapshot-mode supports max_bag_duration argument with max_bag_size 

## Implementation Notes / Suggestions

Possibly look through the cache and split based on time in topic messages 

## Testing Notes / Suggestions

- test snapshot-mode with duration does not make empty bag files
- test snapshot-mode with duration splits bags based on time between messages in the cache

**Comment by emersonknapp** [comment] 2024-08-28 18:40
Closing as duplicate of #900

**Closed as completed by emersonknapp** 2024-08-28 18:40 UTC
Labels: enhancement
