### ISSUE TITLE
rosbag API C++ 

### ISSUE THREAD

**Issue by saimouli** [ros2/rosbag2#141] opened 2019-07-15 20:24 UTC
Suggestions on how to access ros2 bag's info, record and play with a c++ interface? When would documentation about API and examples be anticipated?

**Comment by Karsten1987** [comment] 2019-08-05 18:20
closing this as a duplicate of #126 as there is definitely a need emerging for having a clear C++ API and documentation for it.

The c++ entry point for your tasks such as `info`, `record` and `play` is realized in the rosbag2_transport layer. Precisely this class should get you going:
https://github.com/ros2/rosbag2/blob/master/rosbag2_transport/include/rosbag2_transport/rosbag2_transport.hpp

**Closed by Karsten1987** 2019-08-05 18:20 UTC
