### ISSUE TITLE
records_sensor_data test is flaky

### ISSUE THREAD

**Issue by tfoote** [ros2/rosbag2#766] opened 2021-05-10 21:59 UTC
## Description

records_sensor_data test fails about once per week in nightly builds: https://ci.ros2.org/job/nightly_linux-aarch64_repeated/1590/testReport/rosbag2_transport/RecordIntegrationTestFixture/records_sensor_data/history/

![Screenshot from 2021-05-10 14-57-15](https://user-images.githubusercontent.com/447804/117729679-0ca5ac80-b1a0-11eb-8d8a-35e5229e1c9c.png)

### Expected Behavior
It should pass every nightly.

### Actual Behavior
Be repeatable. 

## To Reproduce
Run the CI repeated nightly tests: https://ci.ros2.org/job/nightly_linux-aarch64_repeated/

## System (please complete the following information)
 - OS: Ubuntu Focal
 - ROS 2 Distro: Nightly
 - Version: head

## Additional context
* From the buildfarmer monitoring.

**Comment by Barry-Xu-2018** [comment] 2021-06-29 05:36
This problem maybe similar to #790.   
While publisher sends messages, subscription of rosbag may not connect to publisher.    

Unfortunately, I cannot reproduce this after run `test_record` 100 times in my local environment.  
After fixing #790, I can update test codes of `test_record`.

**Comment by MichaelOrlov** [comment] 2023-04-13 18:03
- Closing as not reproducible any more
![image](https://user-images.githubusercontent.com/7294722/231845512-6372acb6-2b62-4a19-819b-a42bddae2ad6.png)

**Closed by MichaelOrlov** 2023-04-13 18:03 UTC
Labels: bug, Linux
