### ISSUE TITLE
Add option to CLI to start recorder with warning not info log-level

### ISSUE THREAD

**Issue by bijoua29** [ros2/rosbag2#1255] opened 2023-03-05 16:39 UTC
## Description

When running 'ros2 bag record', I don't want all the normal console output that indicates what topic are being subscribed to. I would like to start the recorder node with 'warning' or 'error' log level instead of info.

## Related Issues

N/A

## Completion Criteria

Add option to 'ros2 bag record' for log level

## Implementation Notes / Suggestions

N/A

## Testing Notes / Suggestions

N/A

**Comment by bijoua29** [comment] 2023-03-12 00:49
A --log-level argument with options debug, info, warn, error, fatal would be the preferred solution

**Comment by emersonknapp** [comment] 2023-06-06 20:40
Closing this one as duplicate of #288

**Closed as completed by emersonknapp** 2023-06-06 20:40 UTC
Labels: enhancement
