### ISSUE TITLE
how to set storage_interfaces::IOFlag::READ_WRITE in python?

### ISSUE THREAD

**Issue by jonbakerfish** [ros2/rosbag2#1233] opened 2023-01-17 01:42 UTC
Hi, is there any document or exmaple for rosbag2_py about modifying existing bag by appending new data to existing topics or creating new topics?

**Comment by emersonknapp** [comment] 2023-02-14 21:16
There isn't actually any support in  rosbag2, currently, for appending data to an existing bag in any language interface. There is an `IOFlag::APPEND` definition that was intended to someday handle this case, but it is not implemented by any interfaces/storage implementations.

**Comment by MichaelOrlov** [comment] 2023-03-17 01:28
- Closing as there are no solution for the question.

**Closed by MichaelOrlov** 2023-03-17 01:28 UTC
Labels: enhancement
