### ISSUE TITLE
[humble] rosbag2_storage linking to yaml-cpp::yaml-cpp 

### ISSUE THREAD

**Issue by PizzocaroSolomon** [ros2/rosbag2#1831] opened 2024-10-11 15:03 UTC
Hello everyone,

We have a project containing targets linking to rosbag2_storage and the standard yaml-cpp library.  
During compilation, we  get the following CMake warning:

<img width="532" alt="image" src="https://github.com/user-attachments/assets/7e12ec49-c657-4256-80ac-cfd48fd7b2cd">

We're certain that all our targets are linking to yaml-cpp using the target `yaml-cpp::yaml-cpp`.

Inside "/opt/ros/humble/share/rosbag2_storage/cmake/export_rosbag2_storageExport.cmake" we noticed the following lines:

`set_target_properties(rosbag2_storage::rosbag2_storage PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/rosbag2_storage"
  INTERFACE_LINK_LIBRARIES "pluginlib::pluginlib;rcpputils::rcpputils;rcutils::rcutils;yaml-cpp"
)
`

and substituting "yaml-cpp" with "yaml-cpp::yaml-cpp", the warning disappears. 

We are convinced that this is a dirty solution to our problem. 
Do you have any suggestions on what we can do to remove the warning cleanly? 
Is it possible to add this "fix" to one of the next releases of ROS2 humble?

thank you very much!

**Comment by clalancette** [comment] 2024-10-11 15:07
Closing as a duplicate of #1830.

**Closed as not planned by clalancette** 2024-10-11 15:07 UTC
Labels: enhancement
