### ISSUE TITLE
Filter a specific transformation from the /tf topic

### ISSUE THREAD

**Issue by imstevenpmwyca** [ros2/rosbag2#886] opened 2021-10-15 14:29 UTC
## Description

Something similar to what this does in ros1:
`rosbag filter mappingData_input.bag mappingData_output.bag 'topic != "/tf" or topic == "/tf" and m.transforms[0].header.frame_id != "map" and m.transforms[0].child_frame_id != "odom"'`

## Completion Criteria

After filtering a bag with a tf that has map->odom->base we get a new bag with a tf that has only odom->base

**Comment by emersonknapp** [comment] 2021-10-15 18:20
Closing as duplicate of #885

**Closed as completed by emersonknapp** 2021-10-15 18:21 UTC
Labels: enhancement
